# Generated by Django 5.2.4 on 2025-09-29 16:36

import django.db.models.deletion
import restaurantes.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=restaurantes.models.categoria_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoRestaurante',
            fields=[
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=255)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('calificacion_promedio', models.FloatField(default=0)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('pagina_web', models.URLField(blank=True, null=True)),
                ('capacidad', models.PositiveIntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=restaurantes.models.restaurante_image_path)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='restaurantes/banners/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurantes.categoriarestaurante')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.estadorestaurante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=restaurantes.models.plato_image_path)),
                ('disponible', models.BooleanField(default=True)),
                ('precio_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='restaurantes.restaurante')),
            ],
        ),
    ]
