# Generated by Django 5.2.4 on 2025-10-10 03:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOpcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('obligatorio', models.BooleanField(default=False)),
                ('multiple', models.BooleanField(default=False)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_opciones', to='restaurantes.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionPlato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='restaurantes.tipoopcion')),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='tipos_opciones',
            field=models.ManyToManyField(blank=True, related_name='platos', to='restaurantes.tipoopcion'),
        ),
    ]
