# Generated by Django 5.2.4 on 2025-10-10 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_tipoopcion_opcionplato_plato_tipos_opciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='tipos_opciones',
        ),
        migrations.AddField(
            model_name='tipoopcion',
            name='plato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_opciones', to='restaurantes.plato'),
        ),
    ]
