# Generated by Django 5.2.4 on 2025-09-29 16:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('icons', models.CharField(blank=True, max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_bs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tasa_cambio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia', models.CharField(blank=True, max_length=50)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.metodopago')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ordenes.orden')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('orden', 'metodo')},
            },
        ),
    ]
