# Generated by Django 5.2.4 on 2025-10-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='telefono_pago',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
