# Generated by Django 5.2.4 on 2025-09-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
