# Generated by Django 5.2.4 on 2025-10-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conductor_latitud_conductor_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
