# Generated by Django 5.2.4 on 2025-10-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conductor_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='icons',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
