# Generated by Django 5.2.4 on 2025-10-02 21:57

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rol_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula_imagen',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.usuario_image_path),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificacion_email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificacion_identidad',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificacion_telefono',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'El teléfono debe tener entre 10 y 15 dígitos, con opción de +')]),
        ),
    ]
