# Generated by Django 5.2.4 on 2025-10-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario_cedula_imagen_usuario_verificacion_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='comentarios_verificacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificacion_intentos',
            field=models.IntegerField(default=0),
        ),
    ]
