# Generated by Django 5.2.4 on 2025-10-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_codigoverificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='expo_token',
            field=models.CharField(blank=True, help_text='Token de notificación Expo', max_length=255, null=True),
        ),
    ]
