# Generated by Django 5.2.4 on 2025-09-29 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('restaurantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoOrden',
            fields=[
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurantes.plato')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('numero_orden', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccion_entrega', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cliente', models.ForeignKey(blank=True, limit_choices_to={'rol__nombre': 'cliente'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_cliente', to=settings.AUTH_USER_MODEL)),
                ('conductor', models.ForeignKey(blank=True, limit_choices_to={'rol__nombre': 'conductor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_cliente', to='core.conductor')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.estadoorden')),
            ],
        ),
    ]
