# Generated by Django 5.2.4 on 2025-09-29 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
        ('pagos', '0001_initial'),
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.metodopago'),
        ),
        migrations.AddField(
            model_name='orden',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurantes.restaurante'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ordenes.orden'),
        ),
    ]
