# Generated by Django 5.2.4 on 2025-09-30 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conductor_latitud_conductor_longitud'),
        ('ordenes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_cliente', to='core.conductor'),
        ),
    ]
