# Generated by Django 5.2.4 on 2025-10-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_orden_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='limite_aceptacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
