# Generated by Django 5.2.4 on 2025-10-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_orden_limite_aceptacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True),
        ),
    ]
