# Generated by Django 5.2.4 on 2025-10-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_alter_orden_latitud_alter_orden_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='costo_envio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
