# Generated by Django 5.2.4 on 2025-10-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_orden_costo_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='movimientos_generados',
            field=models.BooleanField(default=False),
        ),
    ]
