# Generated by Django 5.2.4 on 2025-10-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_orden_movimientos_generados'),
        ('restaurantes', '0003_remove_plato_tipos_opciones_tipoopcion_plato'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='extras',
            field=models.ManyToManyField(blank=True, to='restaurantes.opcionplato'),
        ),
    ]
