# Generated by Django 5.2.4 on 2025-09-29 16:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('conductor_puntaje', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('restaurante_puntaje', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
